<?php

namespace App\Enums;

use BenSampo\Enum\Enum;

/**
 * @method static static LLAMADA_TELEFONICA()
 * @method static static DOCUMENTO_REFERENCIA()
 * @method static static APLICATIVO_MOVIL()
 */
final class AuditoriaUsuariosTipoEnum extends Enum
{


    const CREACION_USUARIO = "CREACIÓN DE USUARIO";
    const BUSQUEDA_USUARIO = "BÚSQUEDA DE USUARIO PARA CREACIÓN/MODIFICACIÓN";
    const SUSPENDER_MI_USUARIO = "SUSPENCIÓN DE USUARIO VOLUNTARIO(A)";
    const ACTIVAR_MI_USUARIO = "ACTIVACIÓN DE USUARIO VOLUNTARIO(A)";
    
    const VERIFICACION_MASPOL = "VERIFICACION DE MASPOL";
    const VERIFICACION_RENIEC = "VERIFICACION DE RENIEC";
    const VERIFICACION_PRIVADA = "VERIFICACION PRIVADA DE INSTITUCIÓN ACADEMICA";

    const VER_USUARIO = "VISTA DE DATOS DE USUARIO PARA MODIFICACIÓN";

    const CAMBIO_DE_ALIAS = "ACTUALIZACIÓN DE ALIAS";
    const CAMBIO_DE_AVATAR = "ACTUALIZACIÓN DE AVATAR";

    const CAMBIO_DE_GRADO = "ACTUALIZACIÓN DE GRADO DE USUARIO";
    const CAMBIO_DE_NOMBRES = "ACTUALIZACIÓN DE NOMBRES DE USUARIO";
    const CAMBIO_DE_APELLIDOS = "ACTUALIZACIÓN DE APELLIDOS DE USUARIO";
    const CAMBIO_DE_DOCUMENTO_IDENTIDAD = "ACTUALIZACIÓN DE DOCUMENTO DE IDENTIDAD";

    const CAMBIO_DE_PROCEDENCIA = "ACTUALIZACIÓN DE PROCEDENCIA";
    const CAMBIO_DE_WHATSAPP = "ACTUALIZACIÓN DE WHATSAPP";

    const CAMBIO_DE_PIN = "RESETEO DE PIN";
    const CAMBIO_UNIDAD = "ACTUALIZACIÓN DE UNIDAD";
    const CAMBIO_DEPARTAMENTO = "ACTUALIZACIÓN DE LOCALIDAD:DEPARTAMENTO";

    const ACTUALIZACION_MODULOS = "ACTUALIZACIÓN DE MODULOS";
    const RECUPERACION_PASSWORD_EMAIL = "RECUPERACIÓN DE CONTRASEÑA POR EMAIL";
    const RECUPERACION_PASSWORD_VIASMS = "RECUPERACIÓN DE CONTRASEÑA POR MENSAJE DE TEXTO";
    const CAMBIO_PASSWORD_DESDE_PLATAFORMA = "CAMBIO DE CONTRASEÑA DESDE LA PLATAFORMA (DIGITADO)";
    const CAMBIO_PASSWORD_DESDE_PLATAFORMA_VIASMS = "CAMBIO DE CONTRASEÑA POR UN ADMINISTRADOR DESDE LA PLATAFORMA (VIA SMS)";
    const CAMBIO_PASSWORD_DESDE_APP_ANDROID = "CAMBIO DE CONTRASEÑA DESDE EL APP-ANDROID (DIGITADO)";
    const CAMBIO_ESTADO_ACTIVO = "ACTIVACIÓN DE USUARIO";
    const CAMBIO_ESTADO_SUSPENDIDO = "SUSPENCIÓN DE USUARIO";
    const CAMBIO_ESTADO_DESACTIVACION_VOLUNTARIO = "SUSPENCIÓN DE USUARIO POR VOLUNTAD PROPIA";
    const CAMBIO_DE_OPERADOR_PERSONAL = "ACTUALIZACIÓN DE OPERADOR DE CELULAR PERSONAL";
    const CAMBIO_DE_CELULAR_PERSONAL = "ACTUALIZACIÓN DE NÚMERO DE CELULAR PERSONAL";
    const CAMBIO_DE_OPERADOR_INSTITUCIONAL = "ACTUALIZACIÓN DE OPERADOR DE CELULAR INSTITUCIONAL";
    const CAMBIO_DE_CELULAR_INSTITUCIONAL = "ACTUALIZACIÓN DE NÚMERO DE CELULAR INSTITUCIONAL";
    const CAMBIO_DE_EMAIL_PERSONAL = "ACTUALIZACIÓN DE EMAIL PERSONAL";
    const CAMBIO_DE_EMAIL_INSTITUCIONAL = "ACTUALIZACIÓN DE EMAIL INSTITUCIONAL";

    const CAMBIO_DE_PERFIL = "ACTUALIZACIÓN DE PERFIL";

    const CARGAR_ACTA = "DOCUMENTO/ACTA DE CREACIÓN/ACTIVACIÓN DE USUARIO";
    const DESCARGAR_ACTA = "DESCARGA DE DOCUMENTO/ACTA DE USUARIO";
    const ELIMINAR_ACTA = "ELIMINO EL DOCUMENTO/ACTA DE USUARIO";
    const DOCUMENTO_SUSPENCION_USUARIO = "DOCUMENTO DE SUSPENCIÓN DE USUARIO";

    const ELIMINAR_DOCUMENTOS_ACTAS = "DOCUMENTO/ACTA ELIMINADO DEL USUARIO";

    const SUGERENCIA = "REGISTRO DE SUGERENCIA";
    const RECLAMO = "REGISTRO DE RECLAMO";

    const SOLICITAR_EMAIL_CONFIRMACION = "SE ENVÍO EL CORREO ELECTRÓNICO DE CONFIRMACIÓN DE USUARIO";
    const SOLICITAR_REENVIO_EMAIL_CONFIRMACION = "SOLICITAR REENVIAR CORREO ELECTRÓNICO DE CONFIRMACIÓN DE USUARIO";

}
